defaults:
  - _self_

seed: 42
checkpoint_name: null  # Use base model

# Model config
model:
  model_name: pythia-70m
  for_training: false
  device_map: auto
  dtype: bfloat16

# Dataset config
dataset:
  dataset_key: wrp
  num_samples: 5

# Inference parameters
inference:
  max_new_tokens: 100
  num_beams: 1
  do_sample: true
  use_cache: true
  temperature: 0.8
  num_return_sequences: 1
  batch_size: 2
  output_suffix: test_generated